### ISSUE TITLE
Does not display dropdown 

### ISSUE THREAD

**Issue by CragVFX** [expandjs/mat-dropdown#1]
Hello,

mat-dropdown does not display the dropdown options if there is only one option. It should display even if there is only one.

Thanks!

**Comment by Pupix** [comment]
Strange. WIll look into it and fix it ASAP.

**Comment by Pupix** [comment]
The issue has been fixed, however this sounds like an edge case where the wrong element is used to get the job done.

For the moment once the user has selected an option, in this case the only possible option, he can't unselect it (you can do it programmatically tho). The Material Design spec doesn't have a way of handling this kind of situation (unsetting a dropdown option), as of yet.

**Comment by CragVFX** [comment]
Awesome, thank you for looking into it so quickly.
