### ISSUE TITLE
How to change Color Scheme?

### ISSUE THREAD

**Issue by ahmedali5530** [expandjs/mat-dropdown#10]
Hi @grullo90 ,
I do not have any issues i m just seeking of how to change the color scheme of dropdown. Are there any custom properties and mixins like Polymer have.

**Comment by grullo90** [comment]
Hi,
at the moment, the only way to do that is by using ::shadow css selector. With the next release, which will be out in a few days, we're going to simplify a lot the internal shadow, adding support for css variables and native ShadowDOM.

**Comment by ahmedali5530** [comment]
Thanks, will wait for next release.
