### ISSUE TITLE
Floating Label

### ISSUE THREAD

**Issue by Inrego** [expandjs/mat-dropdown#2]
Any chance for an option for floating label for this? Once a value is selected, there's no label anymore.. I could use description, but

1: Maybe I want an actual description instead of label there
2: Breaks the design from other elements that use floating label

**Comment by Pupix** [comment]
Thanks for the issue!

We've implemented the floating label and the dropdown should align well with other inputs now.

If you keep having the same problem after updating, clear your bower cache (in case you are using bower) and try a fresh install.

**Comment by Inrego** [comment]
Thank you! When reinstalling, I receive this error:

bower font-roboto#^1.0.0            ENORESTARGET No tag found that was able to satisfy ^1.0.0

EDIT: It looks like it depends on mat-typography, which depends on Polymer/font-roboto - but that element seems to be deprecated, and only for Polymer 0.5

EDIT2: I guess this is the one you meant to add as dependency? PolymerElements/font-roboto#^1.0.0

EDIT3: I created an issue in the right place for this, as it doesn't seem to be a problem with mat-dropdown. Here's a link: https://github.com/expandjs/mat-typography/issues/1

**Comment by Pupix** [comment]
That's what I meant. Fixed it.
