### ISSUE TITLE
Javascript error when value is a number

### ISSUE THREAD

**Issue by Inrego** [expandjs/mat-dropdown#3]
When value of each mat-option binds to a number, a JS error is thrown in the console. It does still seem to work, though.

**Comment by Inrego** [comment]
I was wrong when I said it still does seem to work. It doesn't work at all :/

**Comment by Pupix** [comment]
We are aware of this limitation and a fix should come soon. In the meantime you can use a compute function to transform your number into string and back.

**Comment by Inrego** [comment]
I'll just let it be for now - as I said, it still does work, just throws a random error.

**Comment by Pupix** [comment]
Fixed. Keep in mind that by design the dropdown's model is always a string, even if the values in your options are numbers (just like the `<select>` tag).

If you must access the selected value as a number you can add **type="number"** to the dropdown and all the returned models will be numbers.

**Comment by Inrego** [comment]
Sorry for the delay, been on vacation. I just had a chance to test it. There seems to be an issue when the value is the number 0. The value number 0 will always be converted to string if chosen first.

I'll try to give as much info as possible below:

As a source of data for the dropdown, I have the following array:
![](http://i.imgur.com/yzHIL8D.png)

Here's the HTML:

```
<mat-dropdown reset id="hanoverSignType" floating-label label="Skiltetype" value="{{newSign.SignType}}" type="number">
    <template is="dom-repeat" items="{{config.SignTypes}}">
        <mat-option value="{{item.Value}}" label="{{item.Name}}"></mat-option>
    </template>
</mat-dropdown>
```

And it is drawn correctly, as shown below:
![](http://i.imgur.com/48ThrtT.png)

If I select the first option, which has the value `0`, and then check the value of `newSign.SignType`, the value is the string `"0"`.
If I select any other option, the value of `newSign.SignType` is the equivalent number. And if I select the first option after any of the others have been selected, the value will also be the number `0`.

**Comment by Pupix** [comment]
This is _almost_ working as intended. Value should always be string, just like how `<select>` works.
The fact that you get a string when the `value` is `0` and a number when the `value` is something else is a bug.

`model` is the property that gives you the casted value, `value` is the default value (**type** string) as in native HTML5.

We will cover these cases better in future reviews of the documentation.

**Comment by Pupix** [comment]
**Update:**

Just checked with your data and HTML and everything seems to work. What you are experiencing may be a bug from a previous version. Try to clean your `bower cache` and redownload the dropdown.
