### ISSUE TITLE
No way to reset

### ISSUE THREAD

**Issue by Inrego** [expandjs/mat-dropdown#4]
I can't seem to find any way to reset it, so that no value is picked. I've tried setting the data-bound value to null, but that didn't change anything.

**Comment by Pupix** [comment]
There's a .reset() method on all inputs (from xp-input-behavior), which will return you to the initial status of an input (in this case the dropdown).

We are currently working on a documentation update to highlight this kind interactions with behaviors.

**Comment by Inrego** [comment]
Oh, thank you! Yeah I forgot to look into the behaviors. Documentation on original paper- and iron-elements also suffer badly from lack of documentation of this kind.

**Comment by Pupix** [comment]
Just an update.

The documentation now shows all the **attributes**, **properties**, **methods** and **events** coming from all behaviors and wrapped tags inside an element.
