### ISSUE TITLE
Example with selected value

### ISSUE THREAD

**Issue by phidias51** [expandjs/mat-dropdown#5]
Could you add an example that shows how to bind a value to the dropdown?  There's currently no documentation for this, excepted for the picked method.  I'd like to be able to do something like this:

```
<mat-dropdown id="rsvp" selected="{{selected}}">
      <mat-option value="YES" label="Yes"></mat-option>
      <mat-option value="NO" label="No"></mat-option>
      <mat-option value="MAYBE" label="No"></mat-option>
</mat-dropdown> 

```

**Comment by Pupix** [comment]
The property you are looking for is called "model" (from xp-input-behavior) and it represents the current value of an input (in this case the selected value).

``` html
<mat-dropdown id="rsvp" model="{{selected}}">
      <mat-option value="YES" label="Yes"></mat-option>
      <mat-option value="NO" label="No"></mat-option>
      <mat-option value="MAYBE" label="No"></mat-option>
</mat-dropdown> 
```

We are currently working on a new documentation to highlight the behaviors used and possibly include all the other properties/methods/attributes that come with each behavior.
