### ISSUE TITLE
no menu display with only a single mat-option child

### ISSUE THREAD

**Issue by richardhundt** [expandjs/mat-dropdown#6]
Hi there,

Love this project :+1: 

I found an issue with this component when there is only a single option:

``` HTML
    <mat-dropdown label="Select a value..." floating-label>
        <mat-option value="1" label="Value 1"></mat-option>
    </mat-dropdown>
```

Since I'm generating these from a repeating template, and I have no guarantee that my data set contains more than one item, I'm struggling with this one.  Any ideas?

**Comment by richardhundt** [comment]
``` CSS
:host([single-item]) #matDropdownMenu {
    display: none !important;
}
```

this looks like it's intentional, so what is the correct way of showing and binding in the case of a single item? I'm after a way to trigger an event when a selection changes, even if there is only a single item.

**Comment by Pupix** [comment]
Thanks for the issue!

We've fixed this. You should be able to use the dropdown even with a single option now. 

If you keep having this problem after you redownload the package, try cleaning bower's cache.

Cheers!
