### ISSUE TITLE
TypeError: Cannot read property 'theme' of undefined.

### ISSUE THREAD

**Issue by phidias51** [expandjs/mat-dropdown#7]
I have a project which uses the mat-dropdown component.  It has two dependencies which seem to have problems with themes: mat-paper, and mat-menu. 

Uncaught TypeError: Cannot read property 'theme' of undefined
Polymer.ready   @   mat-paper.html:493

Uncaught TypeError: Cannot read property 'length' of undefined
mat-menu.html:230

Could you take a look at these issues?  I'm using the Sky theme: https://polymerthemes.com/sky/

**Comment by Pupix** [comment]
Hello!

This is the same dependency problem from ExpandJS/mat-paper#1. A fix will land soon.

**Comment by Pupix** [comment]
The issue should be fixed with the new v0.9.4.
