### ISSUE TITLE
programmatic selection via `pick` doesn't update display

### ISSUE THREAD

**Issue by richardhundt** [expandjs/mat-dropdown#8]
Hi, the following doesn't do what I expect:

``` html
<dom-module id="my-elmt">
  <template>
    <mat-dropdown id="myDropdown">
      <mat-option value="0" label="foo"></mat-option>
      <mat-option value="1" label="bar"></mat-option>
      <mat-option value="2" label="baz"></mat-option>
    </mat-dropdown>
  </template>
  <script>
    Polymer({
      is: 'my-elmt',
      ready: function() {
        this.$.myDropdown.pick("1")
      }
    })
  </script>
</dom-module>
```

It seems to update internal state, but no UI feedback.

**Comment by richardhundt** [comment]
Did some more digging and it looks like some kind of life-cycle race condition in initializing the `items` array in Polymer.XPSelectedBehavior. Yielding a time-slice in `ready` before calling `pick` seems to work (obviously a hack, though):

``` JavaScript
    Polymer({
      is: 'my-elmt',
      ready: function() {
        this.async(function() { this.$.myDropdown.pick("1") }, 50)
      }
    })
```

Polymer docs say that `ready` is called after the child subtree has been initialised, so the DOM should all be there, so not sure why the items array is empty, but it seems to be the case (the DOM mutation event used by XPSelectedBehaviour probably runs too early to hook into for populating the items array).

**Comment by Pupix** [comment]
This happens because of he way the mutation observer works.

The polymer docs say that the "**local-dom** child subtree" has been initialized before `ready`, not the light-dom.

To avoid further confusion, we've removed the `pick` method and you can do all the selecting by changing the `value` of the dropdown and it will do everything by itself, rightly timed.
