### ISSUE TITLE
default-selected="0" ignored 

### ISSUE THREAD

**Issue by richardhundt** [expandjs/mat-dropdown#9]
Hi, I want to populate a dropdown's options from an array. I don't know in advance what the values are, but I simply want the first one to be selected, so it seems reasonable to use the `index` as the value:

``` html
<dom-module id="my-elmt">
  <template>
    <mat-dropdown id="myDropdown" default-selected="0">
      <template is="dom-repeat" items="[[values]]">
        <mat-option value="[[index]]" label="[[item]]"></mat-option>
      </template>
    </mat-dropdown>
  </template>
  <script>
    Polymer({
      is: 'my-elmt',
      ready: function() {
        this.values = [ "foo", "bar", "baz" ];
      },
      properties: {
        values: {
          type: Array,
          value: [ ]
        }
      }
    })
  </script>
</dom-module>
```

It turns out that the string `"0"` is special in that it is ignored if I set `default-selected="0"`. Any other numeric value seems to work.

**Comment by richardhundt** [comment]
This relates to #8 as well. Turns out in https://github.com/expandjs/mat-dropdown/blob/master/mat-dropdown.html#L703 you're doing:

``` JavaScript
if (this.selection) { this.value = this.selection.value || ''; }
```

The `value` field has been cast to a `number` type which is false in a boolean context if it is `0`, so this is at least one point where it breaks.

**Comment by Pupix** [comment]
Thanks for finding this bug!

We've just updated the element and everything should be fine now.

Clear your bower cache and redownload the dropdown.

Cheers!

**Comment by richardhundt** [comment]
Works like a charm now, thanks!
